// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "a48eddf70f3589d0e3b97e4bee64c45e26c95e7c60e8b158576ec207bbde6d82")
