// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "21f6d9da831f2bffed5c85e2d198427a2b5f12aaa81f5d218c573f2997aefc20")
