// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "d0274b1b1437ca58084bbfec6a3e954622e943b1294c9a3d30b6d989c45dfa30")
